print("program to divide the tuple into four parts")
t=(100,200,300,400)
t1=tuple([(t[0])])
t2=tuple([(t[1])])
t3=tuple([(t[2])])
t4=tuple([(t[3])])
print("we have this",t)
print("type of t1 is and its value",type(t1),t1)
print("type of t2 is and its value",type(t2),t2)
print("type of t3 is and its value",type(t3),t3)
print("type of t4 is and its value",type(t4),t4)